databases:
  - name: secret_santa
    ipAllowList: []

services:
  - type: web
    name: rails
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: ee102ee0b4cf137f56c3cb4d3bb19eea
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString

  - type: web
    plan: free
    name: name
